### ISSUE TITLE
End of week todo-List

### ISSUE THREAD

**Issue by voxlol** [boozallen/ossportal#24]
## Backend
* [x] Overhaul backend models
* [x] Explicitly decide what to grab from Github API, and what to store in the DB
* [x] Store Team Admins ? 

## Deployment
* [ ] Test docker contain for api
* [ ] Create & Test docker contain for frontend
* [ ] Create & Test docker contain for redis
* [ ] Create & Test docker contain for mongo

## Navigation
* [ ] Breadcrumbs navigation - either reimplement navigation or fix this across all pages

## Main
* [x] Cache current team memberships on the front page
* [x] Caching 2FA? 
* [x] Link - AAD (future)
* [x] Unlink - AAD (future)

## Admin
* [ ] Enable notifications for Repo creation, Join notifications, Turning Repo Public
* [ ] Logging, latest activity

# Organization
* [ ] Membership - Non-public membership visibility guidelines
* [ ] Teams - Request to join send an email + admin notification

**Comment by voxlol** [comment]
See #26
