### ISSUE TITLE
Master checklist

### ISSUE THREAD

**Issue by voxlol** [boozallen/ossportal#6]
* [x] Default private repo, allow public after 
* [ ] SSL for Redis
* [x] MongoDB
* [x] Heroku/Azure/AWS
* [x] Make Docker container
* [x] Move ENV settings for admins only
* [x] Edit pages
